POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkluZGlhbmEiLCJpZCI6IjY0ZTQ2ZTg4NDljODIyODU4ZjkxNGZiZSIsImlhdCI6MTY5MjY5MjEzMH0.cnfODMf6o1mdUlvFEKsk38uPACjGpFxTqf9z45FLy-c

{
    "title": "Indiana hones",
    "author": "David",
    "url": "davyjones.com",
    "likes": 122321
}